### PR TITLE
Include headers for mkstemps

### LINKED ISSUE #41: src/cli.cc is missing #include <unistd.h> for mkstemps

### PR DESCRIPTION
**Pull request by fmang**
Close #41 

@yurivict Could you please try to build this branch?

### CODE REVIEW

**Comment by yurivict** [comment]
I am sorry, but ```unistd.h``` should be included, not ```stdlib.h```, on FreeBSD: https://www.freebsd.org/cgi/man.cgi?query=mkstemp&sektion=3

Since```stdlib.h``` is also missing for Linux,  maybe a correct patch is to add:
```
#include <stdlib.h>
#if defined(__FreeBSD__)
#include <unistd.h>
#endif
```

**Comment by fmang** [comment]
Wow, I did not expect that.

Let’s include both headers unconditionally for better compatibility, in case there are other BSDs that would require unistd too.

**Comment by fmang** [comment]
Let’s merge this. @yurivict Would you like me to release it as 1.5.1 or do you fetch master?

**Comment by yurivict** [comment]
> @yurivict Would you like me to release it as 1.5.1 or do you fetch master?

I would prefer a release.

Thank you.

**Comment by fmang** [comment]
@yurivict Alright! Before that, may I ask you to ensure that the new --edit feature works as expected? It integrates with the system editor and calls the shell, so even if I think the implementation is portable, who knows what may happen. You can invoke it like `EDITOR=vim opustags -e in.opus -o out.opus`.

**Comment by yurivict** [comment]
Ok. I will check this feature when I will update the port.

**Comment by fmang** [comment]
@yurivict If you will I’d like you to test it before I release, in case you find another issue.

**Comment by yurivict** [comment]
@fmang Can you add links to good opus file examples to test it with, because the links on https://opus-codec.org/ are broken.

**Comment by yurivict** [comment]
I tested the current master on FreeBSD 12.2. The ```--edit``` feature works.

**Comment by yurivict** [comment]
There's also this patch in the port that can be upstreamed:
```
--- src/opus.cc.orig    2020-11-08 09:32:46 UTC
+++ src/opus.cc
@@ -23,6 +23,7 @@
 
 #include <opustags.h>
 
+#include <sys/endian.h>
 #include <string.h>
 
 #ifdef __APPLE__
```

**Pull request merged**
