### PR TITLE
Support VISUAL with --edit

### LINKED ISSUE #35: Please support `VISUAL` environment variable for `--edit`
See https://unix.stackexchange.com/questions/4859/visual-vs-editor-what-s-the-difference

For example, I have `EDITOR=emacsclient` so that it works when I have a tty login, and I have `VISUAL=emacsclient -c`, i.e. "open in a new window", for when I have an X (or X-tunnelling) login.

### PR DESCRIPTION
**Pull request by fmang**
@rrthomas Here’s as you suggested. Please tell me if that works for you.

VISUAL is only used if you have a TERM set. I copied the logic of Git again :)

Close #35.

### CODE REVIEW

**Comment by rrthomas** [comment]
If I set `VISUAL=emacsclient`, no problem. If I set `VISUAL="emacsclient -c"` then 

```
error: execvp failed: No such file or directory
```

I presume it is not passing the command to the shell or attempting to tokenize it?

**Comment by fmang** [comment]
The shell is not called indeed.

I guess it works with other tools though, and I don’t know which solution is best between calling the shell after escaping the path name, or tokenizing EDITOR.

`EDITOR='`echo vim`' git commit` works, so Git surely passes EDITOR as is to the shell. I could reuse Git’s escaping logic: https://github.com/git/git/blob/385c171a018f2747b329bcfa6be8eda1709e5abd/quote.c

Tokenizing would be simple to implement too provided we decide not to support weird values like things with backticks.

I’ll try using the shell, and possibly replace execvp by a system() call.

**Comment by rrthomas** [comment]
Or it might be possible to use `wordexp(3)`?

**Comment by fmang** [comment]
> Or it might be possible to use `wordexp(3)`?

Wow, I didn’t know about this function. I tried it and it’s perfect! Thanks for the tip.

**Comment by rrthomas** [comment]
> Or it might be possible to use `wordexp(3)`?

I only found out about it recently and by accident, and I didn't even need it!

**Pull request merged**
